name: AI Review Engine
description: OpenAI integration to review pull requests
title: "[AI Review] "
labels: ["ai", "backend"]
body:
  - type: markdown
    attributes:
      value: "## Integrate OpenAI GPT-4 to review pull requests"
