name: Auth Feature
description: Track GitHub OAuth implementation
title: "[Auth] "
labels: ["auth", "backend"]
body:
  - type: markdown
    attributes:
      value: "## GitHub OAuth Setup and API Integration"
