name: "Auth Feature"
description: "Track GitHub OAuth implementation"
title: "[Auth] "
labels: ["auth", "backend"]
body:
  - type: markdown
    attributes:
      value: "## GitHub OAuth Setup and API Integration"
  - type: checkboxes
    attributes:
      label: Tasks
      options:
        - label: Create GitHub OAuth app (client ID/secret)
        - label: Store secrets in AWS Secrets Manager
        - label: Implement OAuth Lambda handler
        - label: Add /auth/login API route via API Gateway
        - label: Store user session/token in DynamoDB
