name: CI/CD Setup
description: Automate deployment with GitHub Actions and CDK
title: "[CI/CD] "
labels: ["ci-cd", "devops"]
body:
  - type: markdown
    attributes:
      value: "## Automate deployment and testing pipelines"
