name: Documentation & Ops
description: Improve project documentation and visibility
title: "[Docs] "
labels: ["docs", "onboarding"]
body:
  - type: markdown
    attributes:
      value: "## Write developer-friendly documentation and public logs"
