name: "Docs Feature"
description: "Track documentation and onboarding improvements"
title: "[Docs] "
labels: ["docs"]
body:
  - type: markdown
    attributes:
      value: "## Write and maintain project documentation"
  - type: checkboxes
    attributes:
      label: Tasks
      options:
        - label: Create README with architecture diagram
        - label: Add contributing guide
        - label: Write setup instructions
        - label: Document API routes
        - label: Add FAQ or troubleshooting section
