name: Frontend UI
description: Develop micro-frontend components for CodeCheck
title: "[UI] "
labels: ["frontend", "mfe", "typescript"]
body:
  - type: markdown
    attributes:
      value: "## React + Tailwind Micro-Frontends with API Integration"
